### ISSUE TITLE
Case queries cause SR to be split in each digit with a comma

### ISSUE THREAD

**Issue by snub-fighter** [rothdennis/cisco_support#1]
There is a join() call in the CASE API.  
https://github.com/rothdennis/cisco_support/blob/main/cisco_support/case.py

  With join an SR is split like so. 
  693592627 -> 6,9,3,5,9,2,6,2,7
Thus resulting in erroneous cases in the response that are not related to the request.

```

case.py
    def getCaseSummary(self, case_ids: str, sort_by: str = 'UPDATED_DATE') -> dict:
        params = {
            'sort_by': sort_by
        }
        case_ids = ','.join(case_ids)   <<<<<<<<---------------

        url = f'https://api.cisco.com/case/v3/cases/case_ids/{case_ids}'
        r = requests.get(url=url, headers=self.__headers, params=params, verify=self.__verify, proxies=self.__proxies)

        print(r.content)

        return r.json()
```
```

    import json
    from cisco_support import Case
    from pprint import pprint

    client_key = ''"
    client_secret = '"'

    cases = Case(client_key, client_secret)
    SR = cases.getCaseSummary(case_ids='693592627,693592628')
    pprint(SR)

```

A proper query should look like this. 
`GET /case/v3/cases/case_ids/693592627,693592628?sort_by=UPDATED_DATE`
This is what I send when using the case_ids = ','.join(case_ids)
`GET /case/v3/cases/case_ids/6,9,3,5,9,2,6,2,7,,,6,9,3,5,9,2,6,2,8?sort_by=UPDATED_DATE`

**Comment by rothdennis** [comment]
case_ids shouldn't be a string but a list. I'm on it.
