### ISSUE TITLE
API Hosts for calls changing for Okta migration

### ISSUE THREAD

**Issue by ednpnoble** [rothdennis/cisco_support#8]
Cisco is changing the API authentication and URLS for API calls on September 30, 2023.

See https://apiconsole.cisco.com/docs/read/overview/Migrating_Applications

Commit 92b2505 appears to already resolve the Authentication change

However, API calls need to be updated to point to the new host `apix.cisco.com` 

Old API Base URL is: `api.cisco.com`
New API base URL is `apix.cisco.com`

Specific References called out below

## automated_software_distribution.py References (1)
https://github.com/rothdennis/cisco_support/blob/92b2505225f107c6f3ce76c62fdaa2316da48daf/cisco_support/automated_software_distribution.py#L34

## bug.py References (8)
https://github.com/rothdennis/cisco_support/blob/92b2505225f107c6f3ce76c62fdaa2316da48daf/cisco_support/bug.py#L27

https://github.com/rothdennis/cisco_support/blob/92b2505225f107c6f3ce76c62fdaa2316da48daf/cisco_support/bug.py#L41

https://github.com/rothdennis/cisco_support/blob/92b2505225f107c6f3ce76c62fdaa2316da48daf/cisco_support/bug.py#L55

https://github.com/rothdennis/cisco_support/blob/92b2505225f107c6f3ce76c62fdaa2316da48daf/cisco_support/bug.py#L72

https://github.com/rothdennis/cisco_support/blob/92b2505225f107c6f3ce76c62fdaa2316da48daf/cisco_support/bug.py#L89

https://github.com/rothdennis/cisco_support/blob/92b2505225f107c6f3ce76c62fdaa2316da48daf/cisco_support/bug.py#L106

https://github.com/rothdennis/cisco_support/blob/92b2505225f107c6f3ce76c62fdaa2316da48daf/cisco_support/bug.py#L123

https://github.com/rothdennis/cisco_support/blob/92b2505225f107c6f3ce76c62fdaa2316da48daf/cisco_support/bug.py#L140

## case.py References (4)
https://github.com/rothdennis/cisco_support/blob/92b2505225f107c6f3ce76c62fdaa2316da48daf/cisco_support/case.py#L30

https://github.com/rothdennis/cisco_support/blob/92b2505225f107c6f3ce76c62fdaa2316da48daf/cisco_support/case.py#L40

https://github.com/rothdennis/cisco_support/blob/92b2505225f107c6f3ce76c62fdaa2316da48daf/cisco_support/case.py#L56

https://github.com/rothdennis/cisco_support/blob/92b2505225f107c6f3ce76c62fdaa2316da48daf/cisco_support/case.py#L72

## eox.py References (4)
https://github.com/rothdennis/cisco_support/blob/92b2505225f107c6f3ce76c62fdaa2316da48daf/cisco_support/eox.py#L39

https://github.com/rothdennis/cisco_support/blob/92b2505225f107c6f3ce76c62fdaa2316da48daf/cisco_support/eox.py#L60

https://github.com/rothdennis/cisco_support/blob/92b2505225f107c6f3ce76c62fdaa2316da48daf/cisco_support/eox.py#L81

https://github.com/rothdennis/cisco_support/blob/92b2505225f107c6f3ce76c62fdaa2316da48daf/cisco_support/eox.py#L105

## product_information.py References (3)
https://github.com/rothdennis/cisco_support/blob/92b2505225f107c6f3ce76c62fdaa2316da48daf/cisco_support/product_information.py#L29

https://github.com/rothdennis/cisco_support/blob/92b2505225f107c6f3ce76c62fdaa2316da48daf/cisco_support/product_information.py#L41

https://github.com/rothdennis/cisco_support/blob/92b2505225f107c6f3ce76c62fdaa2316da48daf/cisco_support/product_information.py#L53

## serial_number_information.py References (5)
https://github.com/rothdennis/cisco_support/blob/92b2505225f107c6f3ce76c62fdaa2316da48daf/cisco_support/serial_number_information.py#L28

https://github.com/rothdennis/cisco_support/blob/92b2505225f107c6f3ce76c62fdaa2316da48daf/cisco_support/serial_number_information.py#L40

https://github.com/rothdennis/cisco_support/blob/92b2505225f107c6f3ce76c62fdaa2316da48daf/cisco_support/serial_number_information.py#L52

https://github.com/rothdennis/cisco_support/blob/92b2505225f107c6f3ce76c62fdaa2316da48daf/cisco_support/serial_number_information.py#L63

https://github.com/rothdennis/cisco_support/blob/92b2505225f107c6f3ce76c62fdaa2316da48daf/cisco_support/serial_number_information.py#L74

## service_order_return.py References (2)
https://github.com/rothdennis/cisco_support/blob/92b2505225f107c6f3ce76c62fdaa2316da48daf/cisco_support/service_order_return.py#L26

https://github.com/rothdennis/cisco_support/blob/92b2505225f107c6f3ce76c62fdaa2316da48daf/cisco_support/service_order_return.py#L39

## software_suggestions.py References (6)
https://github.com/rothdennis/cisco_support/blob/92b2505225f107c6f3ce76c62fdaa2316da48daf/cisco_support/software_suggestions.py#L29

https://github.com/rothdennis/cisco_support/blob/92b2505225f107c6f3ce76c62fdaa2316da48daf/cisco_support/software_suggestions.py#L41

https://github.com/rothdennis/cisco_support/blob/92b2505225f107c6f3ce76c62fdaa2316da48daf/cisco_support/software_suggestions.py#L66

https://github.com/rothdennis/cisco_support/blob/92b2505225f107c6f3ce76c62fdaa2316da48daf/cisco_support/software_suggestions.py#L78

https://github.com/rothdennis/cisco_support/blob/92b2505225f107c6f3ce76c62fdaa2316da48daf/cisco_support/software_suggestions.py#L90

https://github.com/rothdennis/cisco_support/blob/92b2505225f107c6f3ce76c62fdaa2316da48daf/cisco_support/software_suggestions.py#L115

**Comment by ednpnoble** [comment]
Corrected title as I incorrectly referenced the EoX Version 5 API as if all APIs were version 5.

**Comment by rothdennis** [comment]
url versions have been updated
